### ISSUE TITLE
UI : Text boxes - queries not working.

### ISSUE THREAD

**Issue by nultinator** [ChileBob/YcashExplorer#20]
When entering a block number or viewkey in the text boxes, nothing happens. Also, when I click on an individual block, it acts like it wants to pull up the block, but it is also unresponsive.

**Comment by ChileBob** [comment]
Yep! My bad! :-)

I'm playing with the connectors between the explorer & the node so all that is offline at the moment.

**Comment by ChileBob** [comment]
Move client queries back to websocket server, doing them via remote node connectors isn't working out.

**Comment by ChileBob** [comment]
Fixed...except for viewkey stuff
